In [1]:
import pandas as pd
import numpy as np
import pymongo as db
from pymongo import MongoClient
client = MongoClient()

In [2]:
db=client.Project_3

In [3]:
db.Bigfoot.drop() # drop collection if exists to avoid duplicating

In [4]:
bf_df=pd.read_csv("../Data/Bigfoot_Locations.csv")

In [5]:
bf_df.columns

Index(['X', 'Y', 'OBJECTID_1', 'FID_', 'FID_1', 'name', 'descriptio',
       'timestamp_', 'ObjectId', 'Lon', 'Lat', 'STATE_NAME', 'STATE_FIPS',
       'Year', 'ID', 'sourceCountry', 'ENRICH_FID', 'areaType', 'bufferUnits',
       'bufferUnitsAlias', 'bufferRadii', 'aggregationMethod', 'HasData',
       'FedLandPt', 'CritHabPt', 'NLCDsnIcPt', 'NLCDfrstPt', 'NLCDssgPt',
       'NLCDAgPt', 'NLCDWetPt', 'NLCDDevPt'],
      dtype='object')

In [6]:
state_names=pd.unique(bf_df['STATE_NAME'])

In [7]:
len(state_names)

50

In [8]:
print(state_names)

['Washington' 'Montana' 'Maine' 'North Dakota' 'South Dakota' 'Wyoming'
 'Wisconsin' 'Idaho' 'Vermont' 'Minnesota' 'Oregon' 'New Hampshire' 'Iowa'
 'Massachusetts' 'Nebraska' 'New York' 'Pennsylvania' 'Connecticut'
 'Rhode Island' 'New Jersey' 'Indiana' 'Nevada' 'Utah' 'California' 'Ohio'
 'Illinois' 'Delaware' 'West Virginia' 'Maryland' 'Colorado' 'Kentucky'
 'Kansas' 'Virginia' 'Missouri' 'Arizona' 'Oklahoma' 'North Carolina'
 'Tennessee' 'Texas' 'New Mexico' 'Alabama' 'Mississippi' 'Georgia'
 'South Carolina' 'Arkansas' 'Louisiana' 'Florida' 'Michigan' 'Alaska' ' ']

In [9]:
bf_df = bf_df[bf_df.STATE_NAME != ' ']

In [10]:
bf_df

,X,Y,OBJECTID_1,FID_,FID_1,name,descriptio,timestamp_,ObjectId,Lon,...,aggregationMethod,HasData,FedLandPt,CritHabPt,NLCDsnIcPt,NLCDfrstPt,NLCDssgPt,NLCDAgPt,NLCDWetPt,NLCDDevPt
0,-121.805300,48.640563,1,0,891,1994-1997+,Report 60: Missing Cattle and large footprints...,1994/05/13 00:00:00+00,892,-121.8053,...,BlockApportionment:Landscape.huc12,1,72.1,51.5,5.3,72.5,17.3,0.0,0.9,1.7
1,-121.092200,46.983333,2,1,892,Sep-83,Report 77: Couple hear vocalizations while cam...,1983/09/01 00:00:00+00,893,-121.0922,...,BlockApportionment:Landscape.huc12,1,91.2,19.8,0.5,81.0,15.1,0.1,0.4,2.8
2,-117.676697,46.333327,3,2,893,Jul-00,Report 89: Fishermen hear large animal crashin...,2000/07/24 00:00:00+00,894,-117.6767,...,BlockApportionment:Landscape.huc12,1,36.8,1.0,0.1,23.5,54.7,17.9,1.9,1.9
3,-122.191396,46.047217,4,3,894,Jul-85,Report 270: Campers awakened by late-night vis...,1985/07/01 00:00:00+00,895,-122.1914,...,BlockApportionment:Landscape.huc12,1,21.3,7.7,1.0,68.2,14.6,0.0,0.6,4.5
4,-123.196701,47.561599,5,4,895,Aug-92,Report 283: Couple hear sounds and find footpr...,1992/08/29 00:00:00+00,896,-123.1967,...,BlockApportionment:Landscape.huc12,1,91.0,76.7,3.6,75.0,18.7,0.0,0.3,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3587,-156.749998,69.500001,3588,3587,3163,Mar-88,Report 6486: Special Forces team follows biped...,1988/03/15 00:00:00+00,3164,-156.7500,...,BlockApportionment:Landscape.huc12,1,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3588,-149.766702,61.090852,3589,3588,3164,Dec-03,Report 8792: Four nocturnal hikers get pelted ...,2003/12/12 00:00:00+00,3165,-149.7667,...,BlockApportionment:Landscape.huc12,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3589,-132.733297,55.455500,3590,3589,3165,May-01,Report 8797: Two boys find footprints on Harri...,2001/05/13 00:00:00+00,3166,-132.7333,...,BlockApportionment:Landscape.huc12,1,85.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3590,-155.980996,57.756602,3591,3590,3166,Jul-04,Report 11616: Fishermen find footprints east o...,2004/07/20 00:00:00+00,3167,-155.9810,...,BlockApportionment:Landscape.huc12,1,99.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3591,-142.769104,63.988691,3592,3591,3167,Aug-08,Report 25442: Hunter describes powerful wood k...,2008/08/20 00:00:00+00,3168,-142.7691,...,BlockApportionment:Landscape.huc12,1,53.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:

classes = []
for index, row in bf_df.iterrows():

    if 'Class A' in row['descriptio']:
        classes.append('Class A')
    elif 'Class B' in row['descriptio']:
        classes.append('Class B')
    elif 'Class C' in row['descriptio']:
        classes.append('Class C')
    else:
        classes.append('None')

In [12]:
bf_df['class'] = classes

In [14]:
bf_df.loc[bf_df['class'] == 'Class A' ]

,X,Y,OBJECTID_1,FID_,FID_1,name,descriptio,timestamp_,ObjectId,Lon,...,HasData,FedLandPt,CritHabPt,NLCDsnIcPt,NLCDfrstPt,NLCDssgPt,NLCDAgPt,NLCDWetPt,NLCDDevPt,class
263,-121.708399,45.841702,264,263,2635,Oct-09,Report 26718: Late night road crossing sightin...,2009/10/05 00:00:00+00,2636,-121.7084,...,1,82.0,74.9,0.0,73.3,22.1,0.0,1.2,3.3,Class A
264,-122.622803,46.053333,265,264,2869,1984,"Report 406: Fisherman observes large, bipedal ...",1984/09/01 00:00:00+00,2870,-122.6228,...,1,0.0,1.6,0.1,75.3,18.6,0.0,0.3,5.7,Class A
265,-121.280199,47.317798,266,265,2870,Oct-00,Report 423: Daylight sighting by fisherman nea...,2000/10/08 00:00:00+00,2871,-121.2802,...,1,73.0,20.9,0.9,60.2,24.8,0.0,5.1,4.6,Class A
266,-122.300299,47.027402,267,266,2871,Oct-00,"Report 495: Passing motorist observes a tall, ...",2000/10/07 00:00:00+00,2872,-122.3003,...,1,23.4,23.4,0.2,41.4,14.3,15.7,5.2,23.1,Class A
267,-121.547798,46.295001,268,267,2872,Jul-91,Report 889: Climber has night-time sighting ne...,1991/07/15 00:00:00+00,2873,-121.5478,...,1,99.9,0.0,14.6,75.2,8.7,0.0,0.5,1.0,Class A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3582,-87.677898,45.150001,3583,3582,3102,Jun-04,Report 51317: Motorist has dusk sighting on Hw...,2004/06/20 00:00:00+00,3103,-87.6779,...,1,0.0,0.0,0.3,21.0,2.5,19.0,47.3,8.0,Class A
3583,-142.899998,61.499998,3584,3583,1270,Jun-00,Report 637: Campers' encounter just after dark...,2000/06/16 00:00:00+00,1271,-142.9000,...,1,97.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Class A
3584,-141.566700,62.937499,3585,3584,1273,Jun-04,"Report 9317: Driver on Alcan Highway has noon,...",2004/06/18 00:00:00+00,1274,-141.5667,...,1,27.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Class A
3585,-141.316502,62.773349,3586,3585,1275,Apr-08,Report 23666: Passenger on the Alcan Highway s...,2008/04/23 00:00:00+00,1276,-141.3165,...,1,69.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Class A
3586,-147.814196,64.891389,3587,3586,1276,Jul-09,Report 26604: Daytime sighting of reddish-colo...,2009/07/15 00:00:00+00,1277,-147.8142,...,1,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Class A

In [15]:
for x in range(len(bf_df)):
        results=bf_df.iloc[x,:]
        index=results["ObjectId"].astype('str')
        result=results.to_dict()
        db.Bigfoot.insert_one({"index":index,"data":result})